from pptx import Presentation
from pptx.util import Inches
import os

class ReportAgent:
    def __init__(self):
        self.simple = ""
        self.eda = ""
        self.forecast = ""
        self.df = None

    def receive_data(self, df):
        """Some agents require data; report agent stores it quietly."""
        self.df = df

    def collect(self, simple, eda, forecast):
        self.simple = simple or ""
        self.eda = eda or ""
        self.forecast = forecast or ""

    def generate(self, filename, chart_path=None):
        prs = Presentation()

        # --- Title Slide ---
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = "InsightOps Automated Report"
        slide.placeholders[1].text = "Generated by the AI Multi-Agent System"

        # --- Chart Slide (only if exists) ---
        if chart_path and os.path.exists(chart_path):
            slide = prs.slides.add_slide(prs.slide_layouts[5])
            slide.shapes.title.text = "Generated Chart"

            # Get slide dimensions
            slide_width = prs.slide_width
            slide_height = prs.slide_height

            # Margins
            margin_h = Inches(0.5)
            margin_top = Inches(1.5)

            # Available area
            pic_width = slide_width - 2 * margin_h
            pic_height = slide_height - margin_top - margin_h

            # Add picture filling available box
            left = margin_h
            top = margin_top
            slide.shapes.add_picture(chart_path, left, top, width=pic_width, height=pic_height)

        # --- EDA Slide ---
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Exploratory Data Analysis"
        body = slide.placeholders[1].text_frame
        body.text = self.eda

        # --- Forecast Slide ---
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Forecast Summary"
        body = slide.placeholders[1].text_frame
        body.text = self.forecast

        prs.save(filename)
        return filename
