from pptx import Presentation
from pptx.util import Inches
import os

class ReportAgent:
    def __init__(self):
        self.simple = ""
        self.eda = ""
        self.forecast = ""
        self.df = None

    def receive_data(self, df):
        """Some agents require data; report agent stores it quietly."""
        self.df = df

    def collect(self, simple, eda, forecast):
        self.simple = simple or ""
        self.eda = eda or ""
        self.forecast = forecast or ""

    def generate(self, filename, chart_path=None):
        prs = Presentation()

        # --- Title Slide ---
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = "InsightOps Automated Report"
        slide.placeholders[1].text = "Generated by the AI Multi-Agent System"

        # --- Chart Slide (only if exists) ---
        if chart_path and os.path.exists(chart_path):
            slide = prs.slides.add_slide(prs.slide_layouts[5])
            slide.shapes.title.text = "Generated Chart"

            left = Inches(1)
            top = Inches(1.8)
            width = Inches(8)

            slide.shapes.add_picture(chart_path, left, top, width=width)

        # --- EDA Slide ---
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Exploratory Data Analysis"

        body = slide.placeholders[1].text_frame
        body.text = self.eda

        # --- Forecast Slide ---
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = "Forecast Summary"

        body = slide.placeholders[1].text_frame
        body.text = self.forecast

        prs.save(filename)
        return filename
